### PR TITLE
set src to value from getBestSelectionFromSrcset if possible

### PR DESCRIPTION
**Pull request by heww**
this fix https://github.com/hilongjw/vue-lazyload/issues/136

### CODE REVIEW

**Comment by heww** [comment]
@hilongjw i'm sorry that vue-lazyload.js should rebuild which i missed in this pr.

**Comment by hilongjw** [comment]
@heww well done, I will build locally and publish new version on npm.

**Comment by heww** [comment]
thank you! new version 👏

**Comment by iamdubx** [comment]
This is not working!

**Comment by iamdubx** [comment]
This doesn't fix shit.

**Comment by heww** [comment]
@hackuun please check the offsetWidth of your el's parentNode, it use  parentNode.offsetWidth * scale to get best image url (the first image whose width is bigger than  parentNode.offsetWidth * scale) to load. this pr ensure that if no url found then use the default url.

**Pull request merged**
